name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.11]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true


      - name: Transfer Web
        run: |
          cat > id_rsa <<- EOF
          ${{ secrets.API_SERVER_PRIVATE_KEY }}
          EOF
          chmod 400 id_rsa
          scp -o StrictHostKeyChecking=no -i "id_rsa" -r dist ${{ secrets.API_SERVER_USER }}@${{ secrets.API_SERVER_IP }}:${{ secrets.API_SERVER_DEST }}
          rm id_rsa
